#!/usr/bin/python
# -*- coding: utf-8 -*-
# @date: 2010-06-04
# @author: shell.xu
import sys
import socks
import logging
import pyweb

from p_gfw import DispatchGFW
from p_http import ProxyDirect, ProxyForward, ProxySocks

def make_dis():
    dis = DispatchGFW(ProxyDirect())
    # dis.add_sock(ProxySocks('localhost', 7777))
    return dis
dis = make_dis()

def main(daemon = False):
    # debug_file = open('access.txt', 'w')
    pyweb.ApacheLog(sys.stdout).set_weblog()
    logging.basicConfig(level = logging.DEBUG, filename = 'error.txt')
    serve = pyweb.HttpServer(dis)
    serve.listen(reuse = True)
    if daemon:
        daemon = pyweb.Daemon(serve)
        daemon.lock_pidfile('proxy.pid')
        try:
            try: daemon.run()
            except KeyboardInterrupt: print 'exit.'
        finally: daemon.free_pidfile()
    else:
        serve.run()
        # except KeyboardInterrupt: print 'exit.'

if __name__ == '__main__': main(daemon = False)
